### PR TITLE
[LJPS-24] Assign Skills to Roles

### PR DESCRIPTION
**Pull request by khyechun**
## Context

JIRA ticket: https://g4t7.atlassian.net/jira/software/c/projects/LJPS/issues/LJPS-24

## Approach

**Backend**
Updated POST /api/roles endpoint in RolesRouter.js
1. After role is created, the promise will also create and perform another sql query to assign the skills to the roles in the Job_Role_Skills mapping table.

Updated PUT /api/roles/:id
1. After role is updated, delete all the mapped skills to the given role and re-add the array of skills assigned passed in the request body. (Not sure if deleting all and readding is the best way, but if there is a suggestion for better way, will try to implement)

**Frontend**
1. Updated the RolesModal component.
2. Retrieve all skills and display them in a list as checkboxes.
3. When creating or updating a role, add the assigned skills into the axios request.
4. Checks if at least 1 skill is assigned. If not error message appears.
5. Refactored the error states in the Roles Modal.

**Test**
1. Added test for assigning skills. Test works by creating 2 skills first, then creating a role, and assigning those 2 skills to the roles. If the body message { success : true } then test is passed.

## Checklist

- [x] My branch is up-to-date with the `main` branch
- [x] Unit test written
- [x] Acceptance Criteria considered and implemented

## Test Instruction

1. npm run test
## Risks
Low

### CODE REVIEW

**Review by lanceljr — APPROVED** [review]
Looking good!

**Review by Randyyeo — CHANGES_REQUESTED** [review]
Can you add some unit tests for the endpoints you have created? dont need to be very complex

**Review by ngliye98 — APPROVED** [review]
Looks good to me

**Comment by cnjk060598** [comment]
Looks good!

**Review by Randyyeo — APPROVED** [review]

**Pull request merged**
